language: python
addons:
  postgresql: "9.3"
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.8
install:
  - pip install -r requirements.txt
before_script:
  - export DJANGO_SETTINGS_MODULE=interpreteer.settings.production
  - psql -U postgres -c 'CREATE DATABASE interpreteer;'
  - psql -U postgres -c "CREATE EXTENSION postgis" -d interpreteer
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d interpreteer
script:
  - python manage.py test
